# Generated by Django 3.1.4 on 2020-12-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0003_onlineusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
            ],
        ),
    ]
