# Generated by Django 3.1.4 on 2020-12-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0004_trendingtopics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineUsers',
        ),
    ]
